version: "3.8"
services:
  backend:
    build: ./backend
    command: [ "/app/wait-for-db.sh", "db:5432", "--", "python", "app.py" ]
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MAIL_SERVER: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USE_TLS: true
      MAIL_USERNAME: 3900w16amog@gmail.com
      MAIL_PASSWORD: epoekmdhdlqiletx
      OPENAI_API_KEY: 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
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - /app/node_modules
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: MenuVenu
      POSTGRES_PASSWORD: MenuVenu
      POSTGRES_DB: MenuVenu
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
